const genres = [
  "Fiction",
  "Non-Fiction",
  "Mystery/Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Historical Fiction",
  "Horror",
  "Adventure",
  "Biography/Autobiography",
  "Self-Help/Motivational",
  "Science/Popular Science",
  "Business/Economics",
  "Poetry",
  "Humor",
  "Travel",
  "Children's",
  "Young Adult",
  "Mystery/Crime",
  "Cooking/Food",
  "History",
  "Religion/Spirituality",
  "Art/Photography",
  "Music",
  "Sports/Recreation",
  "Health/Fitness",
  "Psychology",
  "Philosophy",
  "Technology",
  "Education",
];

module.exports = genres;
